version: "3.8"

services:
    reverseproxy:
        build: docker/reverseproxy
        depends_on:
            - nginx
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - "reverseproxy.env"
        volumes:
            - "letsencrypt_etc:/etc/letsencrypt"
            - "letsencrypt_varwww:/var/www/letsencrypt"
        restart: always
    nginx:
        image: nginx:alpine
        restart: always

volumes:
    letsencrypt_etc:
    letsencrypt_varlib:
    letsencrypt_varwww:
